### ISSUE TITLE
Error occurred when doing the minimal example

### ISSUE THREAD

**Issue by rtransformation** [qcscine/chemoton#3]
When I try to follow the minimal example, in second step:
`python3 -m scine_puffin -c puffin.yaml bootstrap`
error occurred:

```
$ python -m scine_puffin -c puffin.yaml bootstrap                                      
Loading configuration: puffin.yaml
Applying environment variables afterwards.

+-----------------+
|  Bootstrapping  |
+-----------------+

Getting Puffin ready for use.


Building SCINE Core/Utils from sources.

Traceback (most recent call last):
  File "/home/xxx/software/miniconda3/envs/scine/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/xxx/software/miniconda3/envs/scine/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/xxx/software/miniconda3/envs/scine/lib/python3.10/site-packages/scine_puffin/__main__.py", line 148, in <module>
    main()
  File "/home/xxx/software/miniconda3/envs/scine/lib/python3.10/site-packages/scine_puffin/__main__.py", line 134, in main
    main_bootstrap(config)
  File "/home/xxx/software/miniconda3/envs/scine/lib/python3.10/site-packages/scine_puffin/__main__.py", line 73, in main_bootstrap
    bootstrap(config)
  File "/home/xxx/software/miniconda3/envs/scine/lib/python3.10/site-packages/scine_puffin/bootstrap.py", line 69, in bootstrap
    core.install(core_build_dir, install_dir, config["resources"]["cores"])
  File "/home/xxx/software/miniconda3/envs/scine/lib/python3.10/site-packages/scine_puffin/programs/utils.py", line 22, in install
    self.scine_module_install(repo_dir, install_dir, ncores)
  File "/home/xxx/software/miniconda3/envs/scine/lib/python3.10/site-packages/scine_puffin/programs/program.py", line 121, in scine_module_install
    repository.remotes.origin.pull()
  File "/home/xxx/software/miniconda3/envs/scine/lib/python3.10/site-packages/git/remote.py", line 1123, in pull
    res = self._get_fetch_info_from_stderr(proc, progress, kill_after_timeout=kill_after_timeout)
  File "/home/xxx/software/miniconda3/envs/scine/lib/python3.10/site-packages/git/remote.py", line 895, in _get_fetch_info_from_stderr
    proc.wait(stderr=stderr_text)
  File "/home/xxx/software/miniconda3/envs/scine/lib/python3.10/site-packages/git/cmd.py", line 834, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git pull -v -- origin
```

I cannot figure out why, can you help me?

**Comment by weymutht** [comment]
Did you attempt to bootstrap repeatedly? Unfortunately, a repeated checkout of a tag fails currently. You need to completely remove the software directory (specified with the `software_dir` key in `puffin.yaml` before you attempt a new bootstrap.

**Comment by rtransformation** [comment]
> Did you attempt to bootstrap repeatedly? Unfortunately, a repeated checkout of a tag fails currently. You need to completely remove the software directory (specified with the `software_dir` key in `puffin.yaml` before you attempt a new bootstrap.

Thank you very much, but another error occurred, I'll try to solve it by myself, thank you again for the reply.

**Comment by rtransformation** [comment]
> Did you attempt to bootstrap repeatedly? Unfortunately, a repeated checkout of a tag fails currently. You need to completely remove the software directory (specified with the `software_dir` key in `puffin.yaml` before you attempt a new bootstrap.

I solved all problems, Thank you very much, you can close this issue up.

**Comment by weymutht** [comment]
Great, thanks!
